# -*- coding: utf-8 -*-
"""AISkillsDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AViV9S4bI4JkgTKVTQB2KLFX62pV0_IZ
"""

!pip install spacy==3.7.5 huggingface_hub

from huggingface_hub import snapshot_download
import spacy

# Download repo contents to Colab storage
model_path = snapshot_download("nestauk/en_skillner")

# Load model directly from folder
nlp = spacy.load(model_path)

job_description = """
We are seeking a Data Scientist proficient in Python, SQL, and machine learning.
Experience with cloud platforms like AWS and Google Cloud is a plus.
Strong communication and problem-solving skills required.
"""

doc = nlp(job_description)
skills_found = {ent.text for ent in doc.ents if ent.label_ == "SKILL"}

print("Top Skills Found:")
for skill in sorted(skills_found):
    print("-", skill)